-- Group
insert into "group" (ref, creation_date) values ('G1', '2021-10-10');
insert into "group" (ref, creation_date) values ('G2', '2021-10-10');
insert into "group" (ref, creation_date) values ('H1', '2022-10-09');
insert into "group" (ref, creation_date) values ('H2', '2022-10-09');
insert into "group" (ref, creation_date) values ('H3', '2022-10-09');
insert into "group" (ref, creation_date) values ('H4', '2023-01-08');

-- Student
insert into student (first_name, last_name, gender, ref, email, phone) values ('Tedi', 'Spurdon', 'Female', 'STD22001', 'tspurdon0@usda.gov', '238 572 3083');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Libbi', 'Ryle', 'Agender', 'STD21002', 'lryle1@delicious.com', '457 739 0178');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Allen', 'Tee', 'Male', 'STD22003', 'atee2@ox.ac.uk', '714 712 9290');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Catriona', 'Laurie', 'Female', 'STD21004', 'claurie3@unicef.org', '736 461 0621');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Ainsley', 'Boas', 'Female', 'STD22005', 'aboas4@moonfruit.com', '736 788 7087');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Dian', 'Abrahamsohn', 'Female', 'STD21006', 'dabrahamsohn5@feedburner.com', '525 448 2377');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Ericha', 'Merkel', 'Female', 'STD22007', 'emerkel6@taobao.com', '106 582 0393');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Nomi', 'Le Blond', 'Female', 'STD21008', 'nleblond7@t.co', '104 264 6232');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Edouard', 'Lygo', 'Male', 'STD22009', 'elygo8@blogspot.com', '227 373 4324');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Gerardo', 'Hartigan', 'Male', 'STD21010', 'ghartigan9@columbia.edu', '316 518 4910');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Dolf', 'Kenshole', 'Male', 'STD22011', 'dkensholea@deviantart.com', '761 138 1634');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Nina', 'Websdale', 'Female', 'STD21012', 'nwebsdaleb@prweb.com', '402 271 2655');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Gabe', 'Brogiotti', 'Male', 'STD22013', 'gbrogiottic@google.com.au', '248 952 6045');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Sascha', 'Packington', 'Female', 'STD21014', 'spackingtond@addtoany.com', '743 737 4995');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Scotti', 'Leyre', 'Male', 'STD22015', 'sleyree@goo.gl', '524 359 3027');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Cesaro', 'Dulwitch', 'Male', 'STD21016', 'cdulwitchf@newyorker.com', '830 725 6937');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Kenn', 'de Banke', 'Male', 'STD22017', 'kdebankeg@tmall.com', '226 888 0655');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Tiphany', 'Withers', 'Female', 'STD21018', 'twithersh@about.me', '620 421 2979');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Leroi', 'Averay', 'Male', 'STD22019', 'laverayi@businessinsider.com', '134 945 8184');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Jaquith', 'Crowest', 'Female', 'STD21020', 'jcrowestj@elpais.com', '886 786 9890');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Jobye', 'Rey', 'Female', 'STD22021', 'jreyk@ebay.co.uk', '391 565 6710');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Sheff', 'Cescoti', 'Male', 'STD21022', 'scescotil@infoseek.co.jp', '346 393 8632');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Jennine', 'Garrud', 'Female', 'STD22023', 'jgarrudm@cam.ac.uk', '479 677 4351');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Juliet', 'Oliffe', 'Female', 'STD21024', 'joliffen@alexa.com', '562 155 2204');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Julie', 'Skipper', 'Male', 'STD22025', 'jskippero@vkontakte.ru', '750 739 8921');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Jereme', 'Reedie', 'Male', 'STD21026', 'jreediep@ycombinator.com', '696 114 4034');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Gusti', 'Abbes', 'Female', 'STD22027', 'gabbesq@devhub.com', '173 889 0197');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Eleanor', 'Marjoribanks', 'Genderqueer', 'STD21028', 'emarjoribanksr@statcounter.com', '920 309 4763');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Lockwood', 'Lazell', 'Male', 'STD22029', 'llazells@icq.com', '333 924 8194');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Roxanne', 'Havile', 'Female', 'STD21030', 'rhavilet@networksolutions.com', '267 213 2145');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Heloise', 'Renne', 'Female', 'STD22031', 'hrenneu@ucoz.com', '372 525 2830');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Mikel', 'Clemente', 'Male', 'STD21032', 'mclementev@histats.com', '253 460 7681');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Ely', 'Heindrick', 'Male', 'STD22033', 'eheindrickw@patch.com', '367 696 5570');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Tobey', 'Growden', 'Genderfluid', 'STD21034', 'tgrowdenx@marketwatch.com', '434 524 7621');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Hasheem', 'Sturdy', 'Male', 'STD22035', 'hsturdyy@weibo.com', '442 879 7738');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Damiano', 'Lawty', 'Male', 'STD21036', 'dlawtyz@naver.com', '984 705 0931');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Gaynor', 'Weiss', 'Female', 'STD22037', 'gweiss10@newsvine.com', '317 755 9118');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Trueman', 'Brockhouse', 'Male', 'STD21038', 'tbrockhouse11@a8.net', '128 885 7296');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Ricca', 'Hoggan', 'Female', 'STD22039', 'rhoggan12@newyorker.com', '516 936 4545');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Ingram', 'Lodewick', 'Male', 'STD21040', 'ilodewick13@symantec.com', '884 825 9251');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Georgetta', 'Kerbey', 'Female', 'STD22041', 'gkerbey14@gov.uk', '994 113 9966');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Willy', 'Joselovitch', 'Female', 'STD21042', 'wjoselovitch15@ted.com', '512 818 1745');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Law', 'Effaunt', 'Male', 'STD22043', 'leffaunt16@examiner.com', '615 831 7928');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Martynne', 'Lawles', 'Polygender', 'STD21044', 'mlawles17@arstechnica.com', '798 943 6707');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Pryce', 'Serrier', 'Male', 'STD22045', 'pserrier18@angelfire.com', '649 727 4222');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Bendix', 'Vequaud', 'Male', 'STD21046', 'bvequaud19@4shared.com', '661 562 2819');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Ruthy', 'Wiltshier', 'Female', 'STD22047', 'rwiltshier1a@weather.com', '953 273 1405');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Pebrook', 'Olyfant', 'Male', 'STD21048', 'polyfant1b@com.com', '881 699 1718');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Corinne', 'Frankland', 'Female', 'STD22049', 'cfrankland1c@craigslist.org', '471 515 5248');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Lorrie', 'Gommery', 'Male', 'STD21050', 'lgommery1d@digg.com', '574 728 3844');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Domeniga', 'Dyton', 'Female', 'STD22051', 'ddyton1e@cargocollective.com', '363 915 1856');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Sheffie', 'Kures', 'Male', 'STD21052', 'skures1f@symantec.com', '282 782 5800');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Wileen', 'Tavener', 'Female', 'STD22053', 'wtavener1g@army.mil', '602 890 8469');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Balduin', 'Bracegirdle', 'Genderqueer', 'STD21054', 'bbracegirdle1h@nymag.com', '916 923 5504');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Malorie', 'Mangion', 'Female', 'STD22055', 'mmangion1i@census.gov', '919 981 5906');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Esther', 'Sushams', 'Female', 'STD21056', 'esushams1j@naver.com', '153 804 4481');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Bea', 'Zapata', 'Female', 'STD22057', 'bzapata1k@ft.com', '384 983 5818');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Danell', 'Bedminster', 'Female', 'STD21058', 'dbedminster1l@nytimes.com', '511 896 1226');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Anne', 'Bicknell', 'Female', 'STD22059', 'abicknell1m@blog.com', '731 717 8913');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Alie', 'Kerford', 'Non-binary', 'STD21060', 'akerford1n@paypal.com', '597 771 3260');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Laural', 'Chesman', 'Female', 'STD22061', 'lchesman1o@nationalgeographic.com', '864 378 2671');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Tammi', 'Feasby', 'Female', 'STD21062', 'tfeasby1p@sina.com.cn', '993 173 0505');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Nicki', 'Frossell', 'Female', 'STD22063', 'nfrossell1q@twitpic.com', '703 187 8047');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Davidde', 'Verrill', 'Male', 'STD21064', 'dverrill1r@last.fm', '357 410 6256');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Pembroke', 'Cruwys', 'Male', 'STD22065', 'pcruwys1s@vimeo.com', '814 815 9329');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Johann', 'MacPike', 'Male', 'STD21066', 'jmacpike1t@cpanel.net', '526 763 1822');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Aldous', 'Savaage', 'Male', 'STD22067', 'asavaage1u@house.gov', '790 683 3556');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Kessia', 'Ostridge', 'Female', 'STD21068', 'kostridge1v@ustream.tv', '523 712 6501');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Elisabetta', 'Wimsett', 'Female', 'STD22069', 'ewimsett1w@slate.com', '269 963 6411');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Horten', 'Smickle', 'Male', 'STD21070', 'hsmickle1x@wp.com', '716 226 4014');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Minta', 'Sheron', 'Female', 'STD22071', 'msheron1y@xrea.com', '812 597 9059');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Kylie', 'Towne', 'Male', 'STD21072', 'ktowne1z@networksolutions.com', '245 255 0231');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Maighdiln', 'Ingarfill', 'Female', 'STD22073', 'mingarfill20@vkontakte.ru', '869 525 6762');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Riva', 'Guerin', 'Bigender', 'STD21074', 'rguerin21@smh.com.au', '833 176 2352');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Chrissy', 'Hue', 'Male', 'STD22075', 'chue22@feedburner.com', '514 337 0493');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Petey', 'Sempill', 'Genderqueer', 'STD21076', 'psempill23@list-manage.com', '707 225 3298');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Mureil', 'Kingscott', 'Female', 'STD22077', 'mkingscott24@google.nl', '846 198 3797');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Prescott', 'Woltering', 'Male', 'STD21078', 'pwoltering25@google.fr', '308 434 1366');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Felicdad', 'Koppeck', 'Female', 'STD22079', 'fkoppeck26@japanpost.jp', '214 406 7028');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Brandy', 'Ortiga', 'Female', 'STD21080', 'bortiga27@vk.com', '411 663 6682');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Maurits', 'Colam', 'Male', 'STD22081', 'mcolam28@hatena.ne.jp', '484 282 4288');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Beverie', 'Ector', 'Female', 'STD21082', 'bector29@princeton.edu', '848 976 4185');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Maynord', 'Rime', 'Male', 'STD22083', 'mrime2a@photobucket.com', '253 293 1175');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Nick', 'Ragsdall', 'Male', 'STD21084', 'nragsdall2b@de.vu', '441 365 2119');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Peyter', 'Gilardone', 'Male', 'STD22085', 'pgilardone2c@reverbnation.com', '700 222 0268');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Desmond', 'Dadge', 'Bigender', 'STD21086', 'ddadge2d@skyrock.com', '634 425 3286');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Anson', 'Roocroft', 'Male', 'STD22087', 'aroocroft2e@constantcontact.com', '939 865 6950');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Lindsy', 'Wevell', 'Agender', 'STD21088', 'lwevell2f@upenn.edu', '874 744 5819');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Papageno', 'Edge', 'Male', 'STD22089', 'pedge2g@qq.com', '479 777 5194');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Benedikt', 'Zanutti', 'Male', 'STD21090', 'bzanutti2h@walmart.com', '722 513 2957');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Prudy', 'Vowden', 'Female', 'STD22091', 'pvowden2i@epa.gov', '895 107 0183');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Oswell', 'Clackers', 'Male', 'STD21092', 'oclackers2j@buzzfeed.com', '438 779 6521');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Cliff', 'Tolussi', 'Male', 'STD22093', 'ctolussi2k@nationalgeographic.com', '781 369 0708');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Vito', 'Straniero', 'Male', 'STD21094', 'vstraniero2l@google.co.uk', '872 514 5888');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Jacquie', 'Culligan', 'Female', 'STD22095', 'jculligan2m@moonfruit.com', '450 887 8803');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Joete', 'Rustidge', 'Female', 'STD21096', 'jrustidge2n@ifeng.com', '719 957 2178');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Dori', 'Tarling', 'Female', 'STD22097', 'dtarling2o@google.pl', '813 770 7187');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Tandie', 'Okenden', 'Female', 'STD21098', 'tokenden2p@furl.net', '814 857 3151');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Read', 'Keppel', 'Agender', 'STD22099', 'rkeppel2q@infoseek.co.jp', '824 961 0274');
insert into student (first_name, last_name, gender, ref, email, phone) values ('Eugene', 'Fortun', 'Male', 'STD22100', 'efortun2r@hc360.com', '974 926 8098');

-- Teaching Units
insert into teaching_units (name) values ('WEB1');
insert into teaching_units (name) values ('WEB2');
insert into teaching_units (name) values ('MOBILE1');
insert into teaching_units (name) values ('PROG1');
insert into teaching_units (name) values ('PROG2');
insert into teaching_units (name) values ('PROG3');
insert into teaching_units (name) values ('DONNÉES1');
insert into teaching_units (name) values ('DONNÉES2');
insert into teaching_units (name) values ('THÉORIE1');
insert into teaching_units (name) values ('IA1');
insert into teaching_units (name) values ('SYS1');
insert into teaching_units (name) values ('SYS2');
insert into teaching_units (name) values ('MGT1');
insert into teaching_units (name) values ('MGT2');

-- Follow
insert into follow (id_student, id_teaching_units) values (52, 10);
insert into follow (id_student, id_teaching_units) values (44, 11);
insert into follow (id_student, id_teaching_units) values (55, 8);
insert into follow (id_student, id_teaching_units) values (19, 7);
insert into follow (id_student, id_teaching_units) values (73, 5);
insert into follow (id_student, id_teaching_units) values (26, 7);
insert into follow (id_student, id_teaching_units) values (58, 4);
insert into follow (id_student, id_teaching_units) values (50, 2);
insert into follow (id_student, id_teaching_units) values (65, 11);
insert into follow (id_student, id_teaching_units) values (14, 2);
insert into follow (id_student, id_teaching_units) values (95, 1);
insert into follow (id_student, id_teaching_units) values (17, 2);
insert into follow (id_student, id_teaching_units) values (56, 11);
insert into follow (id_student, id_teaching_units) values (38, 9);
insert into follow (id_student, id_teaching_units) values (47, 10);
insert into follow (id_student, id_teaching_units) values (5, 14);
insert into follow (id_student, id_teaching_units) values (85, 1);
insert into follow (id_student, id_teaching_units) values (14, 10);
insert into follow (id_student, id_teaching_units) values (19, 7);
insert into follow (id_student, id_teaching_units) values (8, 5);
insert into follow (id_student, id_teaching_units) values (44, 2);
insert into follow (id_student, id_teaching_units) values (22, 13);
insert into follow (id_student, id_teaching_units) values (58, 1);
insert into follow (id_student, id_teaching_units) values (66, 2);
insert into follow (id_student, id_teaching_units) values (73, 14);
insert into follow (id_student, id_teaching_units) values (14, 7);
insert into follow (id_student, id_teaching_units) values (33, 1);
insert into follow (id_student, id_teaching_units) values (9, 6);
insert into follow (id_student, id_teaching_units) values (64, 9);
insert into follow (id_student, id_teaching_units) values (41, 3);
insert into follow (id_student, id_teaching_units) values (99, 6);
insert into follow (id_student, id_teaching_units) values (58, 7);
insert into follow (id_student, id_teaching_units) values (25, 14);
insert into follow (id_student, id_teaching_units) values (31, 4);
insert into follow (id_student, id_teaching_units) values (11, 12);
insert into follow (id_student, id_teaching_units) values (40, 6);
insert into follow (id_student, id_teaching_units) values (75, 12);
insert into follow (id_student, id_teaching_units) values (6, 12);
insert into follow (id_student, id_teaching_units) values (77, 1);
insert into follow (id_student, id_teaching_units) values (10, 10);
insert into follow (id_student, id_teaching_units) values (24, 12);
insert into follow (id_student, id_teaching_units) values (15, 14);
insert into follow (id_student, id_teaching_units) values (78, 7);
insert into follow (id_student, id_teaching_units) values (99, 1);
insert into follow (id_student, id_teaching_units) values (7, 5);
insert into follow (id_student, id_teaching_units) values (47, 5);
insert into follow (id_student, id_teaching_units) values (82, 10);
insert into follow (id_student, id_teaching_units) values (85, 2);
insert into follow (id_student, id_teaching_units) values (3, 10);
insert into follow (id_student, id_teaching_units) values (5, 5);
insert into follow (id_student, id_teaching_units) values (33, 10);
insert into follow (id_student, id_teaching_units) values (95, 9);
insert into follow (id_student, id_teaching_units) values (33, 7);
insert into follow (id_student, id_teaching_units) values (10, 14);
insert into follow (id_student, id_teaching_units) values (95, 12);
insert into follow (id_student, id_teaching_units) values (48, 13);
insert into follow (id_student, id_teaching_units) values (97, 8);
insert into follow (id_student, id_teaching_units) values (85, 1);
insert into follow (id_student, id_teaching_units) values (100, 4);
insert into follow (id_student, id_teaching_units) values (98, 2);
insert into follow (id_student, id_teaching_units) values (11, 12);
insert into follow (id_student, id_teaching_units) values (44, 4);
insert into follow (id_student, id_teaching_units) values (4, 9);
insert into follow (id_student, id_teaching_units) values (2, 14);
insert into follow (id_student, id_teaching_units) values (7, 6);
insert into follow (id_student, id_teaching_units) values (39, 12);
insert into follow (id_student, id_teaching_units) values (57, 14);
insert into follow (id_student, id_teaching_units) values (89, 9);
insert into follow (id_student, id_teaching_units) values (43, 6);
insert into follow (id_student, id_teaching_units) values (68, 10);
insert into follow (id_student, id_teaching_units) values (61, 12);
insert into follow (id_student, id_teaching_units) values (21, 7);
insert into follow (id_student, id_teaching_units) values (55, 6);
insert into follow (id_student, id_teaching_units) values (77, 12);
insert into follow (id_student, id_teaching_units) values (97, 2);
insert into follow (id_student, id_teaching_units) values (2, 6);
insert into follow (id_student, id_teaching_units) values (13, 6);
insert into follow (id_student, id_teaching_units) values (45, 13);
insert into follow (id_student, id_teaching_units) values (73, 14);
insert into follow (id_student, id_teaching_units) values (13, 1);
insert into follow (id_student, id_teaching_units) values (28, 8);
insert into follow (id_student, id_teaching_units) values (91, 1);
insert into follow (id_student, id_teaching_units) values (62, 12);
insert into follow (id_student, id_teaching_units) values (60, 7);
insert into follow (id_student, id_teaching_units) values (11, 6);
insert into follow (id_student, id_teaching_units) values (95, 2);
insert into follow (id_student, id_teaching_units) values (4, 11);
insert into follow (id_student, id_teaching_units) values (10, 10);
insert into follow (id_student, id_teaching_units) values (66, 11);
insert into follow (id_student, id_teaching_units) values (65, 13);
insert into follow (id_student, id_teaching_units) values (81, 2);
insert into follow (id_student, id_teaching_units) values (88, 4);
insert into follow (id_student, id_teaching_units) values (57, 4);
insert into follow (id_student, id_teaching_units) values (69, 14);
insert into follow (id_student, id_teaching_units) values (89, 9);
insert into follow (id_student, id_teaching_units) values (36, 11);
insert into follow (id_student, id_teaching_units) values (98, 1);
insert into follow (id_student, id_teaching_units) values (82, 4);
insert into follow (id_student, id_teaching_units) values (60, 11);
insert into follow (id_student, id_teaching_units) values (85, 10);

-- Course
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-14 20:24:39', 13, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-08-23 16:25:23', 11, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-27 08:01:22', 1, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-24 18:21:13', 8, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-14 23:22:35', 7, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-12 02:46:32', 1, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-05-03 02:46:45', 4, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-06-23 05:23:14', 14, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-15 03:39:54', 1, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-14 13:53:15', 12, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-17 21:35:56', 7, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-23 01:48:32', 5, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-02 07:38:48', 8, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-16 19:40:18', 9, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-24 09:31:41', 3, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-11 17:01:58', 7, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-25 09:22:17', 2, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-02 15:06:24', 10, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2022-09-11 16:44:06', 14, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-22 12:55:24', 5, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-23 10:14:45', 4, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-02 09:57:44', 7, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-13 04:19:44', 12, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-26 19:58:11', 13, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-08 15:54:20', 12, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-06-04 02:51:49', 1, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-25 20:19:20', 12, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2022-09-07 22:20:17', 6, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-20 20:20:23', 9, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-05-10 02:07:47', 9, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-09 11:35:33', 5, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-06-05 22:15:26', 10, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-06 06:31:46', 7, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-06-21 12:00:38', 13, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-29 23:11:03', 11, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-06-06 12:29:22', 10, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-08 03:22:05', 3, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-05-03 01:19:13', 12, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-05-11 14:14:49', 9, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-09-28 15:45:11', 11, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-02-21 15:46:39', 1, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2023-08-02 02:16:14', 5, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-08-10 23:36:45', 10, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-13 04:34:00', 10, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-14 22:51:27', 9, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2023-08-02 05:45:33', 1, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-26 20:25:26', 4, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-20 18:38:33', 3, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-09-27 08:44:05', 3, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-22 10:32:31', 8, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-26 09:11:41', 12, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-08-21 01:51:01', 9, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-02 23:13:53', 11, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-10 21:31:07', 2, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-20 03:24:19', 12, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-28 12:43:48', 12, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-03 07:56:31', 9, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-30 14:15:20', 2, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-08 17:58:55', 7, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-07 20:03:38', 2, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-08-07 23:56:29', 9, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-02-28 04:43:14', 14, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-05-17 10:37:27', 6, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-09-23 13:55:57', 8, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-06-22 17:34:17', 6, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-21 21:09:12', 4, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-05 03:50:08', 9, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-30 01:03:10', 2, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-08 22:36:29', 11, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-05-01 10:24:31', 3, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-16 22:49:37', 5, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-21 03:46:18', 6, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-11 20:50:02', 7, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-15 16:37:18', 10, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-11 03:45:21', 3, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-26 09:52:32', 11, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-17 02:42:22', 12, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-01-15 03:57:53', 11, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-05 08:41:42', 11, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-05 13:14:24', 9, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-25 19:31:50', 6, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-02 14:32:39', 14, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-20 21:02:33', 6, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2022-09-13 11:23:13', 2, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-09 06:56:23', 9, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-30 23:20:18', 10, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-02-01 06:30:02', 7, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2023-05-06 16:22:44', 6, 1);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-16 09:30:41', 11, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-19 01:26:44', 11, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2023-07-03 05:34:59', 2, 4);
insert into course (date_time, id_teaching_units, id_group) values ('2023-08-03 17:22:53', 14, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-03-20 18:38:25', 6, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-08-13 15:05:23', 9, 2);
insert into course (date_time, id_teaching_units, id_group) values ('2023-04-22 16:54:29', 14, 3);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-20 22:10:22', 4, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-10-11 21:25:46', 13, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2022-11-03 14:24:59', 2, 6);
insert into course (date_time, id_teaching_units, id_group) values ('2022-12-09 08:28:37', 3, 5);
insert into course (date_time, id_teaching_units, id_group) values ('2023-02-25 00:36:50', 14, 6);

-- Absence
insert into absence (id_student, id_course) values (12, 53);
insert into absence (id_student, id_course) values (14, 49);
insert into absence (id_student, id_course) values (51, 27);
insert into absence (id_student, id_course) values (13, 65);
insert into absence (id_student, id_course) values (23, 66);
insert into absence (id_student, id_course) values (67, 40);
insert into absence (id_student, id_course) values (17, 86);
insert into absence (id_student, id_course) values (61, 43);
insert into absence (id_student, id_course) values (84, 66);
insert into absence (id_student, id_course) values (92, 74);
insert into absence (id_student, id_course) values (38, 18);
insert into absence (id_student, id_course) values (60, 80);
insert into absence (id_student, id_course) values (73, 86);
insert into absence (id_student, id_course) values (20, 54);
insert into absence (id_student, id_course) values (9, 42);
insert into absence (id_student, id_course) values (67, 35);
insert into absence (id_student, id_course) values (9, 82);
insert into absence (id_student, id_course) values (35, 89);
insert into absence (id_student, id_course) values (37, 9);
insert into absence (id_student, id_course) values (68, 38);
insert into absence (id_student, id_course) values (91, 42);
insert into absence (id_student, id_course) values (40, 10);
insert into absence (id_student, id_course) values (33, 27);
insert into absence (id_student, id_course) values (89, 32);
insert into absence (id_student, id_course) values (92, 71);
insert into absence (id_student, id_course) values (71, 57);
insert into absence (id_student, id_course) values (70, 68);
insert into absence (id_student, id_course) values (49, 63);
insert into absence (id_student, id_course) values (32, 67);
insert into absence (id_student, id_course) values (2, 55);
insert into absence (id_student, id_course) values (80, 39);
insert into absence (id_student, id_course) values (31, 94);
insert into absence (id_student, id_course) values (31, 76);
insert into absence (id_student, id_course) values (22, 40);
insert into absence (id_student, id_course) values (88, 29);
insert into absence (id_student, id_course) values (88, 58);
insert into absence (id_student, id_course) values (72, 97);
insert into absence (id_student, id_course) values (7, 53);
insert into absence (id_student, id_course) values (68, 10);
insert into absence (id_student, id_course) values (53, 4);
insert into absence (id_student, id_course) values (66, 97);
insert into absence (id_student, id_course) values (67, 26);
insert into absence (id_student, id_course) values (7, 10);
insert into absence (id_student, id_course) values (67, 31);
insert into absence (id_student, id_course) values (31, 18);
insert into absence (id_student, id_course) values (87, 31);
insert into absence (id_student, id_course) values (100, 41);
insert into absence (id_student, id_course) values (55, 27);
insert into absence (id_student, id_course) values (23, 44);
insert into absence (id_student, id_course) values (99, 75);
insert into absence (id_student, id_course) values (5, 4);
insert into absence (id_student, id_course) values (72, 50);
insert into absence (id_student, id_course) values (27, 29);
insert into absence (id_student, id_course) values (48, 46);
insert into absence (id_student, id_course) values (72, 23);
insert into absence (id_student, id_course) values (86, 78);
insert into absence (id_student, id_course) values (18, 25);
insert into absence (id_student, id_course) values (80, 76);
insert into absence (id_student, id_course) values (92, 67);
insert into absence (id_student, id_course) values (68, 99);
insert into absence (id_student, id_course) values (78, 86);
insert into absence (id_student, id_course) values (38, 55);
insert into absence (id_student, id_course) values (75, 80);
insert into absence (id_student, id_course) values (49, 93);
insert into absence (id_student, id_course) values (19, 54);
insert into absence (id_student, id_course) values (91, 99);
insert into absence (id_student, id_course) values (10, 74);
insert into absence (id_student, id_course) values (1, 77);
insert into absence (id_student, id_course) values (53, 72);
insert into absence (id_student, id_course) values (72, 11);
insert into absence (id_student, id_course) values (15, 42);
insert into absence (id_student, id_course) values (64, 11);
insert into absence (id_student, id_course) values (48, 15);
insert into absence (id_student, id_course) values (42, 92);
insert into absence (id_student, id_course) values (17, 84);
insert into absence (id_student, id_course) values (67, 30);
insert into absence (id_student, id_course) values (36, 5);
insert into absence (id_student, id_course) values (60, 52);
insert into absence (id_student, id_course) values (95, 47);
insert into absence (id_student, id_course) values (10, 52);
insert into absence (id_student, id_course) values (93, 14);
insert into absence (id_student, id_course) values (64, 85);
insert into absence (id_student, id_course) values (52, 23);
insert into absence (id_student, id_course) values (57, 80);
insert into absence (id_student, id_course) values (48, 77);
insert into absence (id_student, id_course) values (31, 87);
insert into absence (id_student, id_course) values (83, 6);
insert into absence (id_student, id_course) values (58, 37);
insert into absence (id_student, id_course) values (39, 57);
insert into absence (id_student, id_course) values (47, 36);
insert into absence (id_student, id_course) values (25, 72);
insert into absence (id_student, id_course) values (55, 62);
insert into absence (id_student, id_course) values (73, 67);
insert into absence (id_student, id_course) values (87, 34);
insert into absence (id_student, id_course) values (3, 98);
insert into absence (id_student, id_course) values (14, 93);
insert into absence (id_student, id_course) values (30, 95);
insert into absence (id_student, id_course) values (25, 7);
insert into absence (id_student, id_course) values (82, 6);
insert into absence (id_student, id_course) values (25, 76);
